### ISSUE TITLE
ChoiceBox Accepts Negative Values

### ISSUE THREAD

**Issue by jturfanbasis** [webforj/webforj-docs-samples#148]
### **Description**
In the ComboBoxMaxRowView, the "Number of Rows" input field accepts negative values (e.g., -1), which are invalid and should not be allowed.

### **Steps to Reproduce**
1. Go to the `views > lists > combobox > ComboBoxMaxRowView.java` page.
2. Click the decrement button (▼) in the "Number of Rows" input field until the value becomes negative.
3. Click the "Apply" button.

### **Expected Behavior**
The application should validate the input and prevent negative values, displaying an appropriate error message.

https://github.com/user-attachments/assets/3d48bb04-cf0c-4049-86ee-6b1cc177b36a

**Comment by bbrennanbasis** [comment]
[Max row count](https://docs.webforj.com/docs/components/lists/choicebox#max-row-count)

It's ok for the CheckBox to accept negative values. When a number less than or equal to zero is used, the number of rows will automatically adjust to accommodate the content. This demo demonstrates that behavior.

It would be more appropriate to either change the label of the `NumberField`, or give a visual indicator when the max row count is set as a dynamic value.

**Comment by jturfanbasis** [comment]
Thank you for the clarification, Ben.
